### ISSUE TITLE
DAP-09 support

### ISSUE THREAD

**Issue by inahga** [divviup/divviup-android#101]

**Comment by inahga** [comment]
I believe https://github.com/divviup/divviup-android/pull/108 captured all mechanical changes.

I need Janus 0.7 to be fully released (well, it'll actually be 0.8), then I can make a release [according to when we did this last](https://github.com/divviup/divviup-android/pull/55).

Does this all sound right @divergentdave. I feel like I'm missing something...

**Comment by divergentdave** [comment]
Yes, that looks right. I expected this would be a pretty quick upgrade. The release process is also spelled out in our internal documentation repo, and that may be a bit easier to follow.
