### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by divergentdave** [divviup/divviup-android#15]
We need to either set up a self-hosted Maven repository on Google Artifact Registry or apply for an account on Maven Central.

**Comment by divergentdave** [comment]
The main tradeoffs I see between Google Artifact Registry and Maven central are that we'd have to pay for storage and traffic with Google Artifact Registry, naturally, and Maven Central would require us to manage GPG signatures and comply with a few other [requirements](https://central.sonatype.org/publish/requirements/).

**Comment by divergentdave** [comment]
While the Maven Central repository can be added by calling `mavenCentral()`, custom repositories can be added with the following snippet.

```kotlin
maven {
    name = ...
    url = uri(...)
}
```

Maven Central does require PGP signatures in uploaded archives, and the tooling will at least check that the public key used can be fetched from a key server. (presumably signatures are verified as well) However, there's no binding between users and keys, or packages and keys.

Unfortunately, Maven cannot verify signatures made by PGP subkeys, only by the primary key. This is unfortunate, because it limits our key management options. The good news is the Gradle signing plugin at least supports choosing which key to sign with by its hexadecimal ID, so the mere presence of a signing subkey at publishing time won't trip us up.

The Gradle signing plugin can make use of keys via GPG's keyring, via gpg-agent, or by passing an ASCII-armored private key to `useInMemoryPgpKeys()`. (there are relevant snippets at https://central.sonatype.org/publish/publish-gradle/)

We have the following decision tree to choose from:

* Self-host a Maven repository with GCP Artifact Registry. Include the `com.google.cloud.artifactregistry.gradle-plugin` credential helper plugin.
  * Have GitHub Actions authenticate to GCP via OIDC, and compile, package, sign, and publish releases from GHA upon tagging a release.
  * Developers publish from local workstations. (making use of gcloud's Application Default Credentials for authentication)
* Publish to Maven Central
  * Create a shared GPG keyring with just a primary key, upload its public key to various key servers, back it up to 1Password, and store it in a GitHub Actions secret as well. Place a shared OSSRH account's username and password in other GitHub Actions secrets. Compile, package, sign, and publish releases from GHA upon tagging a release.
  * Developers manage their own GPG keyrings, and publish from local workstations.
    * Use a shared OSSRH account for authentication.
    * Use separate OSSRH accounts for each person.

**Comment by inahga** [comment]
I feel strongly that we should publish to Maven Central, following a general strategy of our libraries being available on the commonly accepted package repositories (NPM, crates.io).

> Create a shared GPG keyring with just a primary key, upload its public key to various key servers, back it up to 1Password, and store it in a GitHub Actions secret as well. Place a shared OSSRH account's username and password in other GitHub Actions secrets. Compile, package, sign, and publish releases from GHA upon tagging a release.

This seems fine to me.

I might suggest we store the private key in [GCP Cloud HSM](https://cloud.google.com/kms/docs/hsm) to make accidental exposure impossible. Then use the standard Actions OIDC authentication flow to access the HSM for signing at build-time. 

Unfortunately I don't know off-hand whether this is possible with PGP. [Cloud HSM does](https://cloud.google.com/kms/docs/reference/pkcs11-openssl) expose a PKCS #11 interface. GPG also supports a PKCS #11 interface (this is what it uses to talk to a yubikey), so theoretically the two could be made to work together, although I have not been able to find prior art.

We might also find this strategy useful if we ever have to manage other code signing artifacts (PGP keys for rpms/debs, certificates for Apple and Microsoft). It is generally good practice to have code signing certificates on HSM anyways.

**Comment by divergentdave** [comment]
It looks like there's an issue with OSSRH setting up new users. I can't use the JIRA credentials to log in to Nexus Repository Manager or to upload a snapshot archive. I'm watching a couple JIRA tickets about this issue, hopefully it's cleared up soon.

**Comment by divergentdave** [comment]
We're set up on OSSRH now, and I have successfully published a snapshot from GitHub Actions.
